//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maghaze_shokofe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public int CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerNumber { get; set; }
        public int CustomerMobile { get; set; }
        public string CustomerAddress { get; set; }
    }
}
