//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maghaze_shokofe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public int ItemCode { get; set; }
        public string ItemName { get; set; }
        public int Price { get; set; }
        public Nullable<int> Dicount { get; set; }
        public int Count { get; set; }
    }
}
