//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maghaze_shokofe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shokofeEntities : DbContext
    {
        public shokofeEntities()
            : base("name=shokofeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buy> Buy { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<usrpssw> usrpssw { get; set; }
        public virtual DbSet<DetailBuy> DetailBuy { get; set; }
        public virtual DbSet<DetailSale> DetailSale { get; set; }
    }
}
