//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maghaze_shokofe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public int SaleNumber { get; set; }
        public int CustomerCode { get; set; }
        public int TotalPrice { get; set; }
        public int TotlaDiscount { get; set; }
        public int TotalPardakht { get; set; }
        public System.DateTime Date { get; set; }
    }
}
